### ISSUE TITLE
Incomplete PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by krin-san** [googleads/swift-package-manager-google-programmatic-access-library-ios#2]
PAL iOS and tvOS frameworks explains the use of the following [Required Reason APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):
- `NSPrivacyAccessedAPICategorySystemBootTime`
- `NSPrivacyAccessedAPICategoryUserDefaults`

When scanned with the https://github.com/Wooder/ios_17_required_reason_api_scanner, iOS framework seem to be using more than that:
- `NSPrivacyAccessedAPICategoryFileTimestamp` via a `stat` call

Full scanner output:
```
Used symbols in binary ./swift-package-manager-google-programmatic-access-library-ios/ProgrammaticAccessLibrary/ProgrammaticAccessLibrary.xcframework/ios-arm64_x86_64-simulator/ProgrammaticAccessLibrary.framework/ProgrammaticAccessLibrary: mach_absolute_time, NSUserDefaults
Used symbols in binary ./swift-package-manager-google-programmatic-access-library-ios/ProgrammaticAccessLibrary/ProgrammaticAccessLibrary.xcframework/ios-arm64/ProgrammaticAccessLibrary.framework/ProgrammaticAccessLibrary: mach_absolute_time, NSUserDefaults, stat
Used symbols in binary ./swift-package-manager-google-programmatic-access-library-tvos/GoogleProgrammaticAccessLibrary/ProgrammaticAccessLibrary.xcframework/tvos-arm64/ProgrammaticAccessLibrary.framework/ProgrammaticAccessLibrary: mach_absolute_time, NSUserDefaults
Used symbols in binary ./swift-package-manager-google-programmatic-access-library-tvos/GoogleProgrammaticAccessLibrary/ProgrammaticAccessLibrary.xcframework/tvos-arm64_x86_64-simulator/ProgrammaticAccessLibrary.framework/ProgrammaticAccessLibrary: mach_absolute_time, NSUserDefaults
```

Please prepare a hotfix release adding `NSPrivacyAccessedAPICategoryFileTimestamp` to PrivacyInfo.xcprivacy file in iOS framework.

**Comment by gschoppe** [comment]
Thank you for identifying this issue. We are currently preparing a new release that should include the missing framework in privacyinfo.

**Comment by ericleich** [comment]
@krin-san which version of PAL are you using? Version 2.8.1 should not be using `NSPrivacyAccessedAPICategoryFileTimestamp`.

**Comment by krin-san** [comment]
You're right, @ericleich, after an update it only uses `NSPrivacyAccessedAPICategoryUserDefaults`. I might have used pre-update scan logs by mistake.
